load("@rules_dotnet//dotnet:defs.bzl", "csharp_library")

csharp_library(
    name = "pgv",
    visibility = ["//visibility:public"],
    runtime_deps = [
        "//csharp/pgv-csharp-stub/src/main/csharp/io/envoyproxy/pgv",
    ],
)
