package csharp

const fileTpl = `// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: {{ .File.InputPath }}

namespace {{ csharpPackage .File }};

{{ if isOfFileType . }}

#pragma warning disable 0169, 0414, anyothernumber
public class {{ classNameFile . }}Validator {
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		{{ range .AllMessages }}
		{{ if not (ignored .) -}}
		if (clazz.equals({{ qualifiedName . }})) return new {{ simpleName .}}Validator();
		{{- end }}
		{{- end }}
		return null;
	}

{{ range .AllMessages -}}
	{{- template "msg" . -}}

#pragma warning restore 0169, anythingelse

{{- end }}
}
{{ else }}
/**
* Validates {@code {{ simpleName . }}} protobuf objects.
*/

#pragma warning disable 0169, 0414, anyothernumber

public class {{ classNameMessage .}}Validator implements io.envoyproxy.pgv.ValidatorImpl<{{ qualifiedName . }}>{
	public static io.envoyproxy.pgv.ValidatorImpl validatorFor(Class clazz) {
		if (clazz.equals({{ qualifiedName . }}.class)) return new {{ simpleName .}}Validator();
		{{ range .AllMessages }}
		{{ if not (ignored .) -}}
		if (clazz.equals({{ qualifiedName . }}.class)) return new {{ simpleName .}}Validator();
		{{- end }}
		{{- end }}
		return null;
	}
	{{- template "msgInner" . -}}
	{{ range .AllMessages -}}
	{{- template "msg" . -}}
	{{- end }}
}

#pragma warning restore 0169, anythingelse

{{ end }}
`
